name: Linter

on:
  pull_request:
    branches:
      - "master"

jobs:
  test:
    name: Run Linter
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up Environment
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install NPM dependencies
        run: npm ci --prefer-offline --no-audit
      - name: Linter
        run: npm run lint
